name: DiverseFX
version: '1.6'
main: dev.skir.DiverseFX
api-version: '1.19'
authors: [ Skirtingas ]
description: Display cool visuals easily using resource packs and titles.
website: skir.dev
libraries:
  - de.exlll:configlib-yaml:4.6.1